/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FuelCounterAbi } from "./FuelCounterAbi";

export { FuelCounterAbi__factory } from "./factories/FuelCounterAbi__factory";
